VirtoCommerce/vc-module-marketing

VirtoCommerce.MarketingModule.Data/Model/DynamicContentPublishingGroupEntity.cs
Filled DynamicContentPublishingGroupEntity ContentItems and ContentPlaces collections properly.
=> #10: Fixed SQL error on saving Publishing element.

VirtoCommerce.MarketingModule.Data/Promotions/DynamicPromotion.cs, VirtoCommerce.MarketingModule.Test/DynamicPromotionTests.cs, VirtoCommerce.MarketingModule.Test/VirtoCommerce.MarketingModule.Test.csproj
=> fix Incorrect promotion coupon max usages logic

VirtoCommerce.MarketingModule.Data/Services/EvaluationPolicies/BestRewardPromotionPolicy.cs, VirtoCommerce.MarketingModule.Data/Services/EvaluationPolicies/CombineStackablePromotionPolicy.cs
got rid of undesired behavior with NULL in array
=> fix StoreIds array with items with null value 

.gitignore, VirtoCommerce.MarketingModule.Data/Services/CouponService.cs, VirtoCommerce.MarketingModule.Data/Services/MarketingSearchServiceImpl.cs, VirtoCommerce.MarketingModule.Data/Services/PromotionUsageService.cs
=> Paged search ordering revision

src/VirtoCommerce.MarketingModule.Data/Migrations/20000000000000_UpdateMarketingV2.cs, src/VirtoCommerce.MarketingModule.Data/Repositories/MarketingRepository.cs
https://virtocommerce.atlassian.net/browse/VP-622
=> vp 622 dynamic content items banner fix

src/VirtoCommerce.MarketingModule.Core/Model/DynamicContent/DynamicContentItem.cs, src/VirtoCommerce.MarketingModule.Data/VirtoCommerce.MarketingModule.Data.csproj, src/VirtoCommerce.MarketingModule.Web/VirtoCommerce.MarketingModule.Web.csproj, tests/VirtoCommerce.MarketingModule.Test/VirtoCommerce.MarketingModule.Test.csproj
Changes was moved from vc-module-core
=> Actualization with v2 changes

src/VirtoCommerce.MarketingModule.Web/Module.cs, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/promotion-detail.js
https://virtocommerce.atlassian.net/browse/VP-1280
=> #VP-1280 Promotion gets out-of-memory

src/VirtoCommerce.MarketingModule.Data/Repositories/IMarketingRepository.cs, src/VirtoCommerce.MarketingModule.Data/Repositories/MarketingRepository.cs, src/VirtoCommerce.MarketingModule.Data/Services/CouponService.cs
Check if a coupon exists with the same name in the selected promotion before saving
=> VP-1793 Error when add coupon with same name

src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/promotion-detail.js, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/promotion-detail.tpl.html
- Need to show these options as they are respected in BestReward policy logic;
=> VP-1872: Show Exclusivity and Combine with self for BestReward

src/VirtoCommerce.MarketingModule.Data/Repositories/MarketingRepository.cs
VP-1945: Use dbContext.remove instead of GenericMassRemove
=> VP-1945: Error when delete content item with filled properties

src/VirtoCommerce.MarketingModule.Core/VirtoCommerce.MarketingModule.Core.csproj, src/VirtoCommerce.MarketingModule.Data/VirtoCommerce.MarketingModule.Data.csproj, src/VirtoCommerce.MarketingModule.Web/Localizations/en.VirtoCommerce.Marketing.json, src/VirtoCommerce.MarketingModule.Web/Module.cs, src/VirtoCommerce.MarketingModule.Web/VirtoCommerce.MarketingModule.Web.csproj
https://virtocommerce.atlassian.net/browse/VP-2353
=> Refactor to apply setting values immediately #VP-2353

src/VirtoCommerce.MarketingModule.Web/Content/marketing.css, src/VirtoCommerce.MarketingModule.Web/Scripts/common/marketing-main.js, src/VirtoCommerce.MarketingModule.Web/Scripts/marketing.js
Add marketing main menu service
=> VP-3352 Make a mechanism to allow extend items in the main marketing blade

src/VirtoCommerce.MarketingModule.Web/Scripts/common/marketing-main.js, src/VirtoCommerce.MarketingModule.Web/Scripts/marketing.js
Unsorted list of items in main menu in marketing module 
Add sorting
=> VP-3352: Add sorting to main menu items list

src/VirtoCommerce.MarketingModule.Web/Scripts/common/marketing-main.js, src/VirtoCommerce.MarketingModule.Web/Scripts/marketing.js
Wrong sorting in marketing module main menu list
Add sorting
=> Bug/VP-3352: Sorting for menu items

src/VirtoCommerce.MarketingModule.Core/Model/Promotions/Rewards/AmountBasedReward.cs
Wrong rounding in cart 
Refusal of using allocate method for rounding
=> VP-3848: Fix wrong routing

src/VirtoCommerce.MarketingModule.Data/Services/PromotionService.cs, tests/VirtoCommerce.MarketingModule.Test/DynamicPromotionTests.cs, tests/VirtoCommerce.MarketingModule.Test/VirtoCommerce.MarketingModule.Test.csproj
Test-cover DynamicPromotion cloning
=> VP-5440: Add promotion clone to the PromotionService

src/VirtoCommerce.MarketingModule.Data/Services/CouponService.cs, src/VirtoCommerce.MarketingModule.Data/Services/DynamicContentService.cs, src/VirtoCommerce.MarketingModule.Data/Services/PromotionService.cs, src/VirtoCommerce.MarketingModule.Data/Services/PromotionUsageService.cs
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
Describe the technical details of realization provided by you.
Add any other context or screenshots about the feature request here.
=> VP-5334: Call ClearCache before publish event

src/VirtoCommerce.MarketingModule.Data/Repositories/IMarketingRepository.cs, src/VirtoCommerce.MarketingModule.Data/Repositories/MarketingRepository.cs, src/VirtoCommerce.MarketingModule.Data/Services/DynamicContentService.cs, tests/VirtoCommerce.MarketingModule.Test/DynamicContentServiceUnitTests.cs, tests/VirtoCommerce.MarketingModule.Test/VirtoCommerce.MarketingModule.Test.csproj
Remove children first
add test
=> VP-5771: 500 when user delete content folder with child folders

src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/item-detail.js
Reverts VirtoCommerce/vc-module-marketing#120
=> Revert "VP-6071: Repair save, reset buttons on a content-item detail blade"

src/VirtoCommerce.MarketingModule.Data/Handlers/CouponUsageRecordHandler.cs
https://virtocommerce.atlassian.net/browse/VP-6604
=> VP-6604: Validate PromotionUsages in CouponUsageRecordHandler

src/VirtoCommerce.MarketingModule.Web/Scripts/common/marketing-main.tpl.html, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/promotion-detail.js, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/promotion-detail.tpl.html
https://virtocommerce.atlassian.net/browse/VP-6670
=> VP-6670: Add paged stores loading in promotions UI

src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/promotion-detail.js, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/promotion-list.js, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/widgets/dashboard.js
https://virtocommerce.atlassian.net/browse/VP-6706
=> VP-6706: Ensure that promotion object is always set in promotion detail blade; update responseGroup in requests

src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/item-detail.js, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/itemFolder-detail.js, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/list.js, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/list.tpl.html, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/placeholders/folder-details.js, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/placeholders/list.js, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/placeholders/list.tpl.html, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/placeholders/placeholder-details.js, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/placeholders/placeholder-details.tpl.html, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/publishing/list.js, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/publishing/list.tpl.html, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/publishing/publication-detail.js, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/catalog-entry-list.js, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/coupon-detail.js, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/coupon-import.tpl.html, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/coupon-list.js, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/filter-detail.js, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/promotion-detail.js, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/promotion-expressions.js, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/promotion-list.js, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/promotion-list.tpl.html
=> VP-6366: Replace panel action icons

src/VirtoCommerce.MarketingModule.Web/Scripts/common/marketing-main.js, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/dynamicContent-list.js, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/item-detail.js, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/itemFolder-detail.js, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/list.js, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/placeholders/folder-details.js, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/placeholders/list.js, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/placeholders/placeholder-details.js, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/publishing/list.js, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/publishing/publication-detail.js, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/coupon-import.js, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/coupon-list.js, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/filter-detail.js, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/promotion-detail.js, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/promotion-list.js
=> VP-6864: Fix header icon

src/VirtoCommerce.MarketingModule.Data/Handlers/CouponUsageRecordHandler.cs
Reduce no of stored orders in a hangfire job HandleCouponUsages by adding only new orders to the job.
https://virtocommerce.atlassian.net/browse/PT-863
=> PT-864: Reduce no of stored orders in a hangfire job HandleCouponUsages

src/VirtoCommerce.MarketingModule.Core/Model/Promotions/ProductPromoEntry.cs, src/VirtoCommerce.MarketingModule.Core/Model/Promotions/PromotionEvaluationContext.cs, src/VirtoCommerce.MarketingModule.Data/Services/EvaluationPolicies/BasePromotionPolicy.cs, src/VirtoCommerce.MarketingModule.Data/Services/EvaluationPolicies/BestRewardPromotionPolicy.cs, src/VirtoCommerce.MarketingModule.Data/Services/EvaluationPolicies/CombineStackablePromotionPolicy.cs, src/VirtoCommerce.MarketingModule.Data/Services/EvaluationPolicies/PromotionPolicyBase.cs, src/VirtoCommerce.MarketingModule.Web/Module.cs, tests/VirtoCommerce.MarketingModule.Test/BestRewardPromotionPolicyTest.cs, tests/VirtoCommerce.MarketingModule.Test/CombineStackablePromotionPolicyTest.cs, tests/VirtoCommerce.MarketingModule.Test/DynamicContentServiceUnitTests.cs
https://virtocommerce.atlassian.net/browse/PT-475
=> PT-476 add cache to promoition evaluation

src/VirtoCommerce.MarketingModule.Core/Model/Promotions/ProductPromoEntry.cs, src/VirtoCommerce.MarketingModule.Core/Model/Promotions/PromotionEvaluationContext.cs
https://virtocommerce.atlassian.net/browse/PT-1127
https://github.com/VirtoCommerce/vc-module-marketing/commit/4264065c5ce3d78df317413664d4108197e18e0f#diff-bc694bc33d825cd6418381c2ddbb4a84515dfbc0563abaac5663b2461056b510R114
=> PT-1127 Possible context cache key issues fix

tests/VirtoCommerce.MarketingModule.Test/DynamicPromotionTests.cs
https://virtocommerce.atlassian.net/browse/PT-1234
=> PT-1235: Fix quality bugs

VirtoCommerce.MarketingModule.sln, docs/index.md, samples/VirtoCommerce.MarketingSampleModule.Web/Models/BlockSampleCondition.cs, samples/VirtoCommerce.MarketingSampleModule.Web/Models/SampleCondition.cs, samples/VirtoCommerce.MarketingSampleModule.Web/Models/SamplePromotionConditionAndRewardTreePrototype.cs, samples/VirtoCommerce.MarketingSampleModule.Web/Module.cs, samples/VirtoCommerce.MarketingSampleModule.Web/Readme.md, samples/VirtoCommerce.MarketingSampleModule.Web/Scripts/all-templates.html, samples/VirtoCommerce.MarketingSampleModule.Web/Scripts/module.js, samples/VirtoCommerce.MarketingSampleModule.Web/VirtoCommerce.MarketingSampleModule.Web.csproj, samples/VirtoCommerce.MarketingSampleModule.Web/_module.manifest, samples/VirtoCommerce.MarketingSampleModule.Web/package-lock.json, samples/VirtoCommerce.MarketingSampleModule.Web/package.json, samples/VirtoCommerce.MarketingSampleModule.Web/webpack.config.js
https://virtocommerce.atlassian.net/browse/PT-170
=> PT-170: Add sample dynamic expression extension module for promotion

src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/item-detail.js
https://virtocommerce.atlassian.net/browse/PT-174
My changes are from 37 to 76 rows. Another changes are made by CodeMaid extension text formatting.
=> PT-2073: Save button accessibility

src/VirtoCommerce.MarketingModule.Web/Localizations/en.VirtoCommerce.Marketing.json, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/list.js, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/list.tpl.html, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/placeholders/list.js, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/placeholders/list.tpl.html, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/publishing/add-content-items.js, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/publishing/add-content-items.tpl.html, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/publishing/add-placeholders.js, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/publishing/add-placeholders.tpl.html, src/VirtoCommerce.MarketingModule.Web/Scripts/marketing.js, src/VirtoCommerce.MarketingModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-662
=> PT-663: Update breadcrumbs

src/VirtoCommerce.MarketingModule.Core/Model/DynamicContent/Conditions/CatalogConditions/DynamicContentConditionCategoryIs.cs, src/VirtoCommerce.MarketingModule.Core/Model/DynamicContent/Conditions/CatalogConditions/DynamicContentConditionProductIs.cs, src/VirtoCommerce.MarketingModule.Core/Model/DynamicContent/DynamicContentConditionTreePrototype.cs, src/VirtoCommerce.MarketingModule.Core/Model/DynamicContent/DynamicContentEvaluationContext.cs, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/publishing/publication-detail.tpl.html, src/VirtoCommerce.MarketingModule.Web/Scripts/marketing.js, tests/VirtoCommerce.MarketingModule.Test/DefaultDynamicContentEvaluatorImplTest.cs
https://virtocommerce.atlassian.net/browse/PT-2148
=> PT-2151 added Catalog DynamicContent conditions

src/VirtoCommerce.MarketingModule.Core/VirtoCommerce.MarketingModule.Core.csproj, src/VirtoCommerce.MarketingModule.Data/VirtoCommerce.MarketingModule.Data.csproj, src/VirtoCommerce.MarketingModule.Web/Scripts/marketing.js, src/VirtoCommerce.MarketingModule.Web/VirtoCommerce.MarketingModule.Web.csproj
Make store scope picker as a standard multiple selector
https://virtocommerce.atlassian.net/browse/PT-3496
=> PT-3497: Make store scope picker as a standard multiple selector

CodeCoverage.runsettings, src/VirtoCommerce.MarketingModule.Data/Services/CouponService.cs, src/VirtoCommerce.MarketingModule.Data/Services/PromotionUsageService.cs, src/VirtoCommerce.MarketingModule.Web/Authorization/MarketingAuthorizationHandler.cs, src/VirtoCommerce.MarketingModule.Web/Model/PromotionReward.cs, src/VirtoCommerce.MarketingModule.Web/Module.cs, tests/VirtoCommerce.MarketingModule.Test/CouponServiceTests.cs
Update marketing module
https://virtocommerce.atlassian.net/browse/PT-1957
=> PT-1957: Marketing module quality

tests/VirtoCommerce.MarketingModule.Test/FluentDataExtractors.cs, tests/VirtoCommerce.MarketingModule.Test/MarketingModulePromotionControllerTests.cs
Write tests for MarketingModulePromotionController
https://virtocommerce.atlassian.net/browse/PT-1957
=> PT-1957: Write tests for MarketingModulePromotionController

src/VirtoCommerce.MarketingModule.Data/ExportImport/CsvCouponImporter.cs, src/VirtoCommerce.MarketingModule.Data/VirtoCommerce.MarketingModule.Data.csproj
Update CsvHelper nuget package to latest versions
https://virtocommerce.atlassian.net/browse/PT-3918
=> PT-3918: Update CsvHelper nuget package to latest versions

src/VirtoCommerce.MarketingModule.Data/Services/PromotionService.cs
- Fix missing old object in PromotionChangedEvent;
- Make ClearCache  protected virtual;
- Read promotions in delete to fully pass into event.
https://virtocommerce.atlassian.net/browse/PT-5404
https://virtocommerce.atlassian.net/browse/PT-5409
https://virtocommerce.atlassian.net/browse/PT-5410
=> PT-5404: Fix missing old object in PromotionChangedEvent

src/VirtoCommerce.MarketingModule.Core/VirtoCommerce.MarketingModule.Core.csproj, src/VirtoCommerce.MarketingModule.Data/VirtoCommerce.MarketingModule.Data.csproj, src/VirtoCommerce.MarketingModule.Web/Controllers/Api/MarketingModulePromotionController.cs, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/placeholders/placeholder-details.js, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/coupon-import.js, src/VirtoCommerce.MarketingModule.Web/VirtoCommerce.MarketingModule.Web.csproj, src/VirtoCommerce.MarketingModule.Web/module.manifest, tests/VirtoCommerce.MarketingModule.Test/MarketingModulePromotionControllerTests.cs
Use assets from newly created module instead of the platform
https://virtocommerce.atlassian.net/browse/PT-4135
=> PT-4135: Use assets from newly created module instead of the platform

src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/items/item-detail.js
The "Save" button is not activated after changing name or description of content item
https://virtocommerce.atlassian.net/browse/PT-4378
=> PT-4378: The Save button is not activated

src/VirtoCommerce.MarketingModule.Web/Localizations/en.VirtoCommerce.Marketing.json, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/dynamicContent-list.tpl.html, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/publishing/content-items.tpl.html, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/coupon-import.tpl.html
Fix language in the loc file
https://virtocommerce.atlassian.net/browse/PT-5011
=> PT-5011: Fix language

src/VirtoCommerce.MarketingModule.Web/Scripts/marketing.js
Fixed language in two strings
https://virtocommerce.atlassian.net/browse/PT-5011
=> docs: Small loc fixes

.github/workflows/main.yml, .github/workflows/publish_nugets.yml, Directory.Build.props, samples/VirtoCommerce.MarketingSampleModule.Web/VirtoCommerce.MarketingSampleModule.Web.csproj, src/VirtoCommerce.MarketingModule.Core/VirtoCommerce.MarketingModule.Core.csproj, src/VirtoCommerce.MarketingModule.Data/Repositories/MarketingDbContext.cs, src/VirtoCommerce.MarketingModule.Data/Search/PromotionSearchService.cs, src/VirtoCommerce.MarketingModule.Data/VirtoCommerce.MarketingModule.Data.csproj, src/VirtoCommerce.MarketingModule.Web/VirtoCommerce.MarketingModule.Web.csproj, src/VirtoCommerce.MarketingModule.Web/module.manifest, tests/VirtoCommerce.MarketingModule.Benchmark.IsSatisfiedBy/VirtoCommerce.MarketingModule.Benchmark.IsSatisfiedBy.csproj, tests/VirtoCommerce.MarketingModule.Benchmark.PromoConditions/VirtoCommerce.MarketingModule.Benchmark.PromoConditions.csproj, tests/VirtoCommerce.MarketingModule.Benchmark.PromoPolicies/VirtoCommerce.MarketingModule.Benchmark.PromoPolicies.csproj, tests/VirtoCommerce.MarketingModule.Test/VirtoCommerce.MarketingModule.Test.csproj, tests/VirtoCommerce.MarketingModule.Test/VirtoCommerce.MarketingModule.Tests.csproj
Bump .Net and EF up to 6
https://virtocommerce.atlassian.net/browse/PT-1956
=> PT-1956: Bump .Net and EF up to 6

src/VirtoCommerce.MarketingModule.Web/Module.cs
https://virtocommerce.atlassian.net/browse/PT-7292
=> PT-7292: Remove redundant BuildServiceProvider from the module startup

src/VirtoCommerce.MarketingModule.Data/Services/EvaluationPolicies/PromotionPolicyBase.cs
=> Promotion policy refactoring

src/VirtoCommerce.MarketingModule.Web/Localizations/en.VirtoCommerce.Marketing.json
=> Minor Localization Fixes

VirtoCommerce.MarketingModule.sln, src/VirtoCommerce.MarketingModule.Core/Model/DynamicContent/EvaluateDynamicContentResult.cs, src/VirtoCommerce.MarketingModule.Core/VirtoCommerce.MarketingModule.Core.csproj, src/VirtoCommerce.MarketingModule.Data/Services/DefaultDynamicContentEvaluator.cs, src/VirtoCommerce.MarketingModule.Data/VirtoCommerce.MarketingModule.Data.csproj, src/VirtoCommerce.MarketingModule.ExperienceApi/AssemblyMarker.cs, src/VirtoCommerce.MarketingModule.ExperienceApi/Queries/EvaluateDynamicContentQuery.cs, src/VirtoCommerce.MarketingModule.ExperienceApi/Queries/EvaluateDynamicContentQueryBuilder.cs, src/VirtoCommerce.MarketingModule.ExperienceApi/Queries/EvaluateDynamicContentQueryHandler.cs, src/VirtoCommerce.MarketingModule.ExperienceApi/Schemas/DynamicContentItemType.cs, src/VirtoCommerce.MarketingModule.ExperienceApi/Schemas/EvaluateDynamicContentResultType.cs, src/VirtoCommerce.MarketingModule.ExperienceApi/VirtoCommerce.MarketingModule.ExperienceApi.csproj, src/VirtoCommerce.MarketingModule.Web/Module.cs, src/VirtoCommerce.MarketingModule.Web/VirtoCommerce.MarketingModule.Web.csproj, src/VirtoCommerce.MarketingModule.Web/module.manifest
https://virtocommerce.atlassian.net/browse/PT-9992
=> PT-9992: Add XAPI for Dynamic content

src/VirtoCommerce.MarketingModule.Core/Model/DynamicContent/Search/DynamicContentPublicationSearchCriteria.cs, src/VirtoCommerce.MarketingModule.Data/Search/ContentPublicationsSearchService.cs, src/VirtoCommerce.MarketingModule.ExperienceApi/Queries/EvaluateDynamicContentQuery.cs
https://virtocommerce.atlassian.net/browse/PT-10164
=> PT-10164: Change toDate query filter type and behaviour

src/VirtoCommerce.MarketingModule.Data.MySql/Migrations/20230222143109_RenameIndex.Designer.cs, src/VirtoCommerce.MarketingModule.Data.MySql/Migrations/20230222143109_RenameIndex.cs, src/VirtoCommerce.MarketingModule.Data.MySql/Migrations/MarketingDbContextModelSnapshot.cs, src/VirtoCommerce.MarketingModule.Data.PostgreSql/Migrations/20230222142801_Initial.Designer.cs, src/VirtoCommerce.MarketingModule.Data.PostgreSql/Migrations/20230222142801_Initial.cs, src/VirtoCommerce.MarketingModule.Data.PostgreSql/Migrations/MarketingDbContextModelSnapshot.cs, src/VirtoCommerce.MarketingModule.Data.SqlServer/Migrations/20230222143038_RenameIndex.Designer.cs, src/VirtoCommerce.MarketingModule.Data.SqlServer/Migrations/20230222143038_RenameIndex.cs, src/VirtoCommerce.MarketingModule.Data.SqlServer/VirtoCommerce.MarketingModule.Data.SqlServer.csproj, src/VirtoCommerce.MarketingModule.Data/Repositories/MarketingDbContext.cs, src/VirtoCommerce.MarketingModule.Web/module.manifest
fix: Rename Index for PostgreSql.
https://virtocommerce.atlassian.net/browse/PT-10853
=> PT-10853: Rename Index for PostgreSql.

src/VirtoCommerce.MarketingModule.Web/package-lock.json, src/VirtoCommerce.MarketingModule.Web/package.json, src/VirtoCommerce.MarketingModule.Web/webpack.config.js
feat: add nodejs-lts support
https://virtocommerce.atlassian.net/browse/PT-9395
=> PT-9395: add nodejs-lts support

.editorconfig, Directory.Build.props, VirtoCommerce.MarketingModule.sln.DotSettings, module.ignore, samples/VirtoCommerce.MarketingSampleModule.Web/VirtoCommerce.MarketingSampleModule.Web.csproj, src/VirtoCommerce.MarketingModule.Core/ModuleConstants.cs, src/VirtoCommerce.MarketingModule.Core/VirtoCommerce.MarketingModule.Core.csproj, src/VirtoCommerce.MarketingModule.Data.MySql/VirtoCommerce.MarketingModule.Data.MySql.csproj, src/VirtoCommerce.MarketingModule.Data.PostgreSql/VirtoCommerce.MarketingModule.Data.PostgreSql.csproj, src/VirtoCommerce.MarketingModule.Data.SqlServer/VirtoCommerce.MarketingModule.Data.SqlServer.csproj, src/VirtoCommerce.MarketingModule.Data/ExportImport/MarketingExportImport.cs, src/VirtoCommerce.MarketingModule.Data/Search/PromotionSearchService.cs, src/VirtoCommerce.MarketingModule.Data/VirtoCommerce.MarketingModule.Data.csproj, src/VirtoCommerce.MarketingModule.Web/Module.cs, src/VirtoCommerce.MarketingModule.Web/VirtoCommerce.MarketingModule.Web.csproj, src/VirtoCommerce.MarketingModule.Web/module.manifest, tests/VirtoCommerce.MarketingModule.Benchmark.IsSatisfiedBy/VirtoCommerce.MarketingModule.Benchmark.IsSatisfiedBy.csproj, tests/VirtoCommerce.MarketingModule.Benchmark.PromoConditions/VirtoCommerce.MarketingModule.Benchmark.PromoConditions.csproj, tests/VirtoCommerce.MarketingModule.Benchmark.PromoPolicies/VirtoCommerce.MarketingModule.Benchmark.PromoPolicies.csproj, tests/VirtoCommerce.MarketingModule.Test/VirtoCommerce.MarketingModule.Test.csproj
https://virtocommerce.atlassian.net/browse/PT-10449
=> PT-10449: Use updated Crud and Search services

Directory.Build.props, samples/VirtoCommerce.MarketingSampleModule.Web/VirtoCommerce.MarketingSampleModule.Web.csproj, src/VirtoCommerce.MarketingModule.Core/VirtoCommerce.MarketingModule.Core.csproj, src/VirtoCommerce.MarketingModule.Data.MySql/VirtoCommerce.MarketingModule.Data.MySql.csproj, src/VirtoCommerce.MarketingModule.Data.PostgreSql/VirtoCommerce.MarketingModule.Data.PostgreSql.csproj, src/VirtoCommerce.MarketingModule.Data.SqlServer/VirtoCommerce.MarketingModule.Data.SqlServer.csproj, src/VirtoCommerce.MarketingModule.Data/Repositories/MarketingDbContext.cs, src/VirtoCommerce.MarketingModule.Data/VirtoCommerce.MarketingModule.Data.csproj, src/VirtoCommerce.MarketingModule.Web/VirtoCommerce.MarketingModule.Web.csproj, src/VirtoCommerce.MarketingModule.Web/module.manifest, tests/VirtoCommerce.MarketingModule.Benchmark.IsSatisfiedBy/VirtoCommerce.MarketingModule.Benchmark.IsSatisfiedBy.csproj, tests/VirtoCommerce.MarketingModule.Benchmark.PromoConditions/VirtoCommerce.MarketingModule.Benchmark.PromoConditions.csproj, tests/VirtoCommerce.MarketingModule.Benchmark.PromoPolicies/VirtoCommerce.MarketingModule.Benchmark.PromoPolicies.csproj, tests/VirtoCommerce.MarketingModule.Test/BestRewardPromotionPolicyTest.cs, tests/VirtoCommerce.MarketingModule.Test/CombineStackablePromotionPolicyTest.cs, tests/VirtoCommerce.MarketingModule.Test/VirtoCommerce.MarketingModule.Test.csproj, tests/VirtoCommerce.MarketingModule.Test/VirtoCommerce.MarketingModule.Tests.csproj
feat: Update to net8
https://virtocommerce.atlassian.net/browse/PT-14740
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Marketing_3.800.0-pr-220-813e.zip
=> PT-14740: Update to net8

src/VirtoCommerce.MarketingModule.Core/Model/Promotions/Rewards/PaymentRewards/RewardPaymentGetOfAbs.cs, src/VirtoCommerce.MarketingModule.Core/Model/Promotions/Rewards/PaymentRewards/RewardPaymentGetOfRel.cs, tests/VirtoCommerce.MarketingModule.Test/BestRewardPromotionPolicyTest.cs
fix: Resolved issue with promotions not being applied to certain payment methods.
https://virtocommerce.atlassian.net/browse/VCST-162
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Marketing_3.801.0-pr-221-4d0e.zip
=> VCST-162: Fix promotion for payment method

samples/VirtoCommerce.MarketingSampleModule.Web/Properties/launchSettings.json, src/VirtoCommerce.MarketingModule.Core/Model/DynamicContent/DynamicContentConditionTreePrototype.cs, src/VirtoCommerce.MarketingModule.Core/Model/Promotions/PromotionConditionAndRewardTreePrototype.cs, src/VirtoCommerce.MarketingModule.Core/VirtoCommerce.MarketingModule.Core.csproj, src/VirtoCommerce.MarketingModule.Web/Scripts/common/marketing-main.tpl.html, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/promotion-detail.tpl.html
* Use a new UserGroupIsCondition for creating promotions
* Change layout in the promotion details blade
* use permission restrictions in Promotion actions blade
https://virtocommerce.atlassian.net/browse/VCST-272
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Marketing_3.802.0-pr-222-1aa3.zip
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Marketing_3.802.0-pr-222-1b7b.zip
=> VCST-272: register a new condition for promotions

src/VirtoCommerce.MarketingModule.Core/Model/Promotions/Conditions/CartConditions/PaymentIsCondition.cs, src/VirtoCommerce.MarketingModule.Core/Model/Promotions/Conditions/CartConditions/ShipmentIsCondition.cs, src/VirtoCommerce.MarketingModule.Core/Model/Promotions/Conditions/CatalogConditions/ConditionEntryIs.cs, src/VirtoCommerce.MarketingModule.Core/Model/Promotions/PromotionConditionAndRewardTreePrototype.cs, src/VirtoCommerce.MarketingModule.Core/Model/Promotions/Rewards/PaymentRewards/RewardPaymentGetOfAbs.cs, src/VirtoCommerce.MarketingModule.Core/Model/Promotions/Rewards/PaymentRewards/RewardPaymentGetOfRel.cs, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicConditions/templates.html, src/VirtoCommerce.MarketingModule.Web/Scripts/marketing.js, tests/VirtoCommerce.MarketingModule.Test/BestRewardPromotionPolicyTest.cs
* add PaymentIsCondition
* add ShippingIsCondition
* register them in the backend
* register them in the frontend
https://virtocommerce.atlassian.net/browse/VCST-328
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Marketing_3.803.0-pr-225-c57e.zip
=> VCST-328: add conditions for paymentType and shippingType

src/VirtoCommerce.MarketingModule.Data/Services/EvaluationPolicies/BestRewardPromotionPolicy.cs, src/VirtoCommerce.MarketingModule.Data/Services/EvaluationPolicies/CombineStackablePromotionPolicy.cs, tests/VirtoCommerce.MarketingModule.Test/BestRewardPromotionPolicyTest.cs, tests/VirtoCommerce.MarketingModule.Test/CombineStackablePromotionPolicyTest.cs
* Use the same logic for the exclusive promotion and the others.
* Fixed a typo in the variable name (evalPromtionTasks => evalProm**o**tionTasks)
https://virtocommerce.atlassian.net/browse/VCST-1
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Marketing_3.805.0-pr-223-a148.zip
=> VCST-1: The shipping discount Amount counts for each selected item but not in a whole cart

src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/coupon-list.tpl.html, src/VirtoCommerce.MarketingModule.Web/Scripts/promotion/blades/promotion-list.tpl.html
feat: Remove Conter from Search panel
https://virtocommerce.atlassian.net/browse/VCST-972
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Marketing_3.806.0-pr-228-bbf0.zip
=> VCST-972: Remove Counter from Search panel

src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/placeholders/list.tpl.html, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/publishing/add-content-items.tpl.html, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/publishing/add-placeholders.tpl.html, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicContent/blades/publishing/list.tpl.html
https://virtocommerce.atlassian.net/browse/VCST-803
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Marketing_3.808.0-pr-230-15aa.zip
=> VCST-803: change id of some templates to avoid duplicates

src/VirtoCommerce.MarketingModule.Web/Localizations/de.VirtoCommerce.Marketing.json, src/VirtoCommerce.MarketingModule.Web/Localizations/en.VirtoCommerce.Marketing.json, src/VirtoCommerce.MarketingModule.Web/Localizations/es.VirtoCommerce.Marketing.json, src/VirtoCommerce.MarketingModule.Web/Localizations/fr.VirtoCommerce.Marketing.json, src/VirtoCommerce.MarketingModule.Web/Localizations/it.VirtoCommerce.Marketing.json, src/VirtoCommerce.MarketingModule.Web/Localizations/ja.VirtoCommerce.Marketing.json, src/VirtoCommerce.MarketingModule.Web/Localizations/pl.VirtoCommerce.Marketing.json, src/VirtoCommerce.MarketingModule.Web/Localizations/pt.VirtoCommerce.Marketing.json, src/VirtoCommerce.MarketingModule.Web/Localizations/ru.VirtoCommerce.Marketing.json, src/VirtoCommerce.MarketingModule.Web/Localizations/zh.VirtoCommerce.Marketing.json, src/VirtoCommerce.MarketingModule.Web/Scripts/common/marketing-main.tpl.html, src/VirtoCommerce.MarketingModule.Web/Scripts/marketing.js
fix: Some titles are not localized
https://virtocommerce.atlassian.net/browse/VCST-2177
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Marketing_3.814.0-pr-238-7b24.zip
=> VCST-2177: Some titles are not localized

src/VirtoCommerce.MarketingModule.Core/Model/Promotions/PromotionEvaluationContext.cs, src/VirtoCommerce.MarketingModule.Core/Model/Promotions/Rewards/AmountBasedReward.cs, src/VirtoCommerce.MarketingModule.Core/Model/Promotions/Rewards/ItemRewards/RewardItemForEveryNumInGetOfRel.cs, src/VirtoCommerce.MarketingModule.Core/Model/Promotions/Rewards/ItemRewards/RewardItemGetOfAbsForNum.cs, src/VirtoCommerce.MarketingModule.Core/Model/Promotions/Rewards/ItemRewards/RewardItemGetOfRel.cs, src/VirtoCommerce.MarketingModule.Core/Model/Promotions/Rewards/ItemRewards/RewardItemGetOfRelForNum.cs, src/VirtoCommerce.MarketingModule.Core/VirtoCommerce.MarketingModule.Core.csproj, src/VirtoCommerce.MarketingModule.Data.MySql/VirtoCommerce.MarketingModule.Data.MySql.csproj, src/VirtoCommerce.MarketingModule.Data.PostgreSql/VirtoCommerce.MarketingModule.Data.PostgreSql.csproj, src/VirtoCommerce.MarketingModule.Data.SqlServer/VirtoCommerce.MarketingModule.Data.SqlServer.csproj, src/VirtoCommerce.MarketingModule.Data/Services/EvaluationPolicies/BestRewardPromotionPolicy.cs, src/VirtoCommerce.MarketingModule.Data/Services/EvaluationPolicies/CombineStackablePromotionPolicy.cs, src/VirtoCommerce.MarketingModule.Data/Services/EvaluationPolicies/PromotionPolicyBase.cs, src/VirtoCommerce.MarketingModule.Data/VirtoCommerce.MarketingModule.Data.csproj, src/VirtoCommerce.MarketingModule.Web/Module.cs, src/VirtoCommerce.MarketingModule.Web/module.manifest, tests/VirtoCommerce.MarketingModule.Benchmark.PromoPolicies/PolicyBenchmark.cs, tests/VirtoCommerce.MarketingModule.Test/BestRewardPromotionPolicyTest.cs, tests/VirtoCommerce.MarketingModule.Test/CombineStackablePromotionPolicyTest.cs, tests/VirtoCommerce.MarketingModule.Test/VirtoCommerce.MarketingModule.Test.csproj
https://virtocommerce.atlassian.net/browse/VCST-2305
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Marketing_3.815.0-pr-240-3db3.zip
=> VCST-2305: Use currency settings when rounding reward amount

.nuke, .nuke/parameters.json, samples/VirtoCommerce.MarketingSampleModule.Web/Models/SamplePromotionConditionAndRewardTreePrototype.cs, src/VirtoCommerce.MarketingModule.Core/Model/DynamicContent/DynamicContentConditionTreePrototype.cs, src/VirtoCommerce.MarketingModule.Core/Model/Promotions/PromotionConditionAndRewardTreePrototype.cs, src/VirtoCommerce.MarketingModule.Core/VirtoCommerce.MarketingModule.Core.csproj, src/VirtoCommerce.MarketingModule.Data.MySql/VirtoCommerce.MarketingModule.Data.MySql.csproj, src/VirtoCommerce.MarketingModule.Data.PostgreSql/VirtoCommerce.MarketingModule.Data.PostgreSql.csproj, src/VirtoCommerce.MarketingModule.Data.SqlServer/VirtoCommerce.MarketingModule.Data.SqlServer.csproj, src/VirtoCommerce.MarketingModule.Data/VirtoCommerce.MarketingModule.Data.csproj, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicConditions/templates.html, src/VirtoCommerce.MarketingModule.Web/Scripts/marketing.js, src/VirtoCommerce.MarketingModule.Web/module.manifest, tests/VirtoCommerce.MarketingModule.Test/BestRewardPromotionPolicyTest.cs, tests/VirtoCommerce.MarketingModule.Test/CombineStackablePromotionPolicyTest.cs, tests/VirtoCommerce.MarketingModule.Test/DefaultDynamicContentEvaluatorImplTest.cs, tests/VirtoCommerce.MarketingModule.Test/DynamicPromotionTests.cs, tests/VirtoCommerce.MarketingModule.Test/VirtoCommerce.MarketingModule.Test.csproj
https://virtocommerce.atlassian.net/browse/VCST-2470
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Marketing_3.817.0-pr-244-f76e.zip
=> VCST-2470: Move promotion expression templates from the core module

src/VirtoCommerce.MarketingModule.Core/Model/Promotions/Conditions/CatalogConditions/ConditionEntryIs.cs, src/VirtoCommerce.MarketingModule.Core/Model/Promotions/ProductPromoEntry.cs, src/VirtoCommerce.MarketingModule.Core/Model/Promotions/PromotionEvaluationContextExtension.cs, src/VirtoCommerce.MarketingModule.Web/Scripts/dynamicConditions/templates.html
https://virtocommerce.atlassian.net/browse/VCST-3519
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Marketing_3.819.0-pr-246-c7a1.zip
=> VCST-3519: Add ApplyToAllVariants flag to product condition
